### ISSUE TITLE
Pluralization doesn't seem to work

### ISSUE THREAD

**Issue by lhtdesignde** [alexdrel/i18n-react#14]
Hi, great small library you got there. Works fine for us just one little thing with the pluralization.
Maybe I understood it wrong but it doesn't seem to work for me.

I'm giving in the quantity for a string. In my yml i have:
```
    longTime:
      1: '{quantity} day no see'
      '2..99': '{quantity} days no see'
```

I'm calling it the following way, quantity is dynamic:
`quantityPerDay = T.translate(`longTime.${quantity}`, {quantity: quantity});`   

When quantity is 1 it shows the correct string. '1 day no see'. But as soon as quantity is more than 1 it just prints out the string 'longTime.2'. So it seems it can't find the pluralized translation.

Am I doing something wrong here? Do I need to call the the plural differently?

**Comment by alexdrel** [comment]
Hi,
There are two issues in the snippet:

1. The translation key should NOT be dynamic but static ```longTime``` w/o suffix.
2. In order to be used for pluralization the quantity has to be passed as ```context```.

Please see a complete pluralization example/unit test at:
https://github.com/alexdrel/i18n-react/blob/master/tests/context_test.ts#L99-L123

**Comment by lhtdesignde** [comment]
cool thanks for the help! Now this is much clearer.
This worked:
quantityPerDay = T.translate(longTime, {quantity: quantity});
