### ISSUE TITLE
Change text dynamically after it is set

### ISSUE THREAD

**Issue by bastoune** [alexdrel/i18n-react#42]
Hey,

I would like to dynamically change the textSet but if I call `T.setTexts(require('../texts/texts-en.yml'));` after already called another yml, it doesn't reload text.

How could I acheive it ?

**Comment by alexdrel** [comment]
Probably the issue is that you have not re-rendered your components once the ```setTexts``` was called. Try ```forceUpdate``` on the root component - should be enough for vanilla React.

**Comment by variousauthors** [comment]
If you are using Redux you can achieve automatic reloading whenever the locale changes by keeping the current locale in your store (via a reducer) and then wrapping T in a connected component. Here's how I've done it for `T.span`:
 
```tsx
interface ITranslationSpan {
  text: {
    key: string
    [val: string]: string | number | JSX.Element
  } | string
}

type TranslationSpanProps = React.HTMLAttributes<HTMLSpanElement> & ITranslationText

const span = connect((state: IState, props: TranslationSpanProps) => {
  return {
    lang: state.locale.code, // <-- this causes the component to re-render when locale changes
    ...props
  }

})((props: TranslationSpanProps) => {
  const rest = R.omit(['dispatch'], props)

  return <Translation.span {...rest} />
})

const T = {
  span
}

export default T
```

Now whenever I use `<T.span text="something"/>` in my components, I can re-render _just_ the translated text (rather than the entire component, or the entire app) by changing the locale in the redux store.
